org: orgDemo
app: appDemo
stage: dev
component: scf
name: scfDemo

inputs:
  src: ./src
  runtime: Nodejs10.15
  region: ap-guangzhou
  handler: index.main_handler
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: GET
