component: scf
name: scf-demo
org: test
app: scfApps
stage: dev
inputs:
  name: scfFunctionDemo
  runtime: Nodejs10.15
  region: ap-guangzhou
  handler: index.main_handler
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          serviceName:
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /index
              method: GET
